// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxap6OY89jVbBaAaVZamIcxx4x7F5Mx3M',
    appId: '1:470027033928:web:c202c19b95ae059c50277d',
    messagingSenderId: '470027033928',
    projectId: 'one-room-b42b0',
    authDomain: 'one-room-b42b0.firebaseapp.com',
    storageBucket: 'one-room-b42b0.firebasestorage.app',
    measurementId: 'G-9Z5V89JXZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVHsibhmP5bsTdXa3zgRXLpT2XiyAvs0',
    appId: '1:470027033928:android:8dc84d57ef28373b50277d',
    messagingSenderId: '470027033928',
    projectId: 'one-room-b42b0',
    storageBucket: 'one-room-b42b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApopf3xRLfmDwDR6pgs05v8FGY7Gqv3y0',
    appId: '1:470027033928:ios:b8c2f9dd93bbb24550277d',
    messagingSenderId: '470027033928',
    projectId: 'one-room-b42b0',
    storageBucket: 'one-room-b42b0.firebasestorage.app',
    iosClientId: '470027033928-r1ea7lo9pjr81fninb7q13ad8foljrm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApopf3xRLfmDwDR6pgs05v8FGY7Gqv3y0',
    appId: '1:470027033928:ios:b8c2f9dd93bbb24550277d',
    messagingSenderId: '470027033928',
    projectId: 'one-room-b42b0',
    storageBucket: 'one-room-b42b0.firebasestorage.app',
    iosClientId: '470027033928-r1ea7lo9pjr81fninb7q13ad8foljrm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxap6OY89jVbBaAaVZamIcxx4x7F5Mx3M',
    appId: '1:470027033928:web:2c30873c24f691d450277d',
    messagingSenderId: '470027033928',
    projectId: 'one-room-b42b0',
    authDomain: 'one-room-b42b0.firebaseapp.com',
    storageBucket: 'one-room-b42b0.firebasestorage.app',
    measurementId: 'G-E99DNP5FRE',
  );

}